---
title: "2027449 - PERCEPCION REMOTA AVANZADA"
subtitle: "Academic Year: 2023"
format: html
---
## PREREQUISITOS:
- Aprobación del curso *Percepción Remota*
- Aprobación del curso *Programación SIG*

## DESCRIPCIÓN DE LA ASIGNATURA:
::: {.callout-important collapse=false}
### OBJETIVOS:
-	Entender el proceso de percepción remota de la superficie terrestre y su relación con la investigación
-	Conocer los principios físicos de la percepción remota basada en radar de apertura sintética (SAR)
-	Entender las características principales de las imágenes y los métodos de corrección radiométrica y geométrica de imágenes SAR
-	Aplicar métodos y técnicas avanzadas para obtener información temática a partir de imágenes ópticas y SAR

### COMPETENCIAS GENÉRICAS: 
-	Comprensión de los fundamentos teóricos de la percepción remota
-	Obtención de habilidades prácticas para seleccionar, procesar y analizar imágenes
-	Desarrollo de pensamiento crítico sobre las ventajas y las limitaciones de la percepción remota

### COMPETENCIAS ESPECÍFICAS:
- Entendimiento del flujo de trabajo genérico  de percepción remota
- Adaptación y creación de scripts para  procesamiento y análisis de imágenes
-	Evaluación de la calidad de productos de percepción remota

### METODOLOGIA:
-	Lectura antes de la clase a cargo del estudiante
-   Presentación de conceptos, métodos y técnicas a cargo del profesor
-	Realización de ejercicios prácticos y elaboración de reportes técnicos a cargo  del estudiante

### SOFTWARE
-  *PARTE 1:* Sentinel-1 Toolbox (S1TBX) 
-  *PARTE 2:* Python & Jupyter & Google Colaboratory
:::


## CONTENIDO DETALLADO 

::: {.callout-important collapse=true}

## PARTE 1 – RADAR DE APERTURA SINTETICA (SAR)

### Semana 1 –   Repaso, Contexto & Conceptos claves

### Semana 2 -  Conceptos básicos de radar

### Semana 3 - Procesamiento básico de imágenes SAR - SNAP

### Semana 4 – Propiedades radiativas de suelos y vegetación

### Semana 5 – Procesamiento básico de imágenes SAR - GEE - JS

### Semana 6 –  Procesamiento básico de imágenes SAR - GEE - Python

### Semana 7 – Analysis Ready SAR Data 

### Semana 8 – Open Data Cube
:::

::: {.callout-important collapse=true}

## PARTE 2 – APRENDIZAJE PROFUNDO  (DEEP LEARNING)

### Semana 9 – Fundamentos de Deep Learning (DL)

### Semana 10  – Redes neuronales convolucionales

### Semana 11 - Clasificación de imágenes 

### Semana 12 - Segmentación semántica I

### Semana 13 - Deep Learning for remote sensing

### Semana 14 -  Segmentación semántica II

### Semana 15 - Aplicaciones DL en vegetación

### Semana 16 - Aplicaciones DL en recursos hídricos
:::

## EVALUACIÓN DEL CURSO: 

::: {.callout-important collapse=false}

-	Presentación de dos exámenes escritos sobre aspectos teóricos (50%)
    - Examen 1 - 20 de Septiembre
    - Examen 2 - 22 de Noviembre
-	Entrega de dos informes técnicos  (50%)
    - Informe 1 - 27 de Septiembre
    - Informe 2 - 29 de Noviembre

:::

## BIBLIOGRAFIA

::: {.callout-important collapse=true}

Chollet, F. Deep Learning with Python [2nd ed.],  Manning, 2021. 504 pp.

De Grandi, G.D. et al. Spatial Analysis for Radar Remote Sensing of Tropical Forests, CRC Press, 2021. 380pp.

Flores-Anderson, A.I. et al. The Synthetic Aperture Radar (SAR) Handbook: Comprehensive Methodologies for Forest Monitoring and Biomass Estimation,  SERVIR GLOBAL & SilvaCarbon, 2019. 307 pp.

Frery, A.C. et al. SAR Image Analysis - A Computational Statistics Approach: With R Code, Data, and Applications, Wiley-IEEE Press, 2022. 208 pp.

Kamusoko, C., Optical and SAR Remote Sensing of Urban Areas: A Practical Guide, Springer, 2021. 130 pp.

Mandal, D. et al. Radar Remote Sensing for Crop Biophysical Parameter Estimation, Springer, 2021. 236 pp.

Raff, E. Inside Deep Learning – Math, Algorithms, Models,  Manning, 2022. 565 pp.

Rees, W.G. Physical Principles of Remote Sensing [3rd ed.],  Cambridge University Press, 2012. 494 pp.

Richards, J.A. Remote Sensing Digital Image Analysis Sensing [6th ed.], Springer, 2022. 567 pp.

Simms, E.L. SAR Image Interpretation for Various Land Covers – A Practical Guide. CRC Press, 2011. 376 pp. 

Ustin, S.L., and Middleton E.M. Current and near-term advances in Earth observation for ecological applications. Ecological Processes, 2021, 10:1 
Woodhouse, I.H. Introduction to Microwave Remote Sensing, Taylor & Francis, 2022. 370 pp. 

Yamaguchi, Y. Polarimetric SAR imaging: theory and applications. CRC Press, 2020. 350 pp.

:::
