---
title: "2027449 - PERCEPCION REMOTA AVANZADA"
subtitle: "Academic Year: 2024"
format: html
---
## PREREQUISITOS:
- Aprobación del curso *Percepción Remota*
- Aprobación del curso *Programación SIG*

## DESCRIPCIÓN DE LA ASIGNATURA:
::: {.callout-important collapse=false}
### OBJETIVOS:
-	Profundizar en tópicos avanzados  de percepción remota de la superficie terrestre 
-	Conocer los principios físicos de la percepción remota de radar de apertura sintética (SAR)
-	Entender las características principales de las imágenes SAR y los métodos de corrección aplicables
-	Aplicar métodos y técnicas de *deep learning* para obtener información temática a partir de imágenes ópticas y SAR

### COMPETENCIAS GENÉRICAS: 
-	Comprensión de los fundamentos teóricos de la percepción remota de la superficie terrestre
-	Obtención de habilidades computacionales para seleccionar, procesar y analizar imágenes
-	Desarrollo de pensamiento crítico sobre las ventajas y las limitaciones de diferentes técnicas

### COMPETENCIAS ESPECÍFICAS:
- Entendimiento del flujo de trabajo genérico  de percepción remota
- Adaptación y creación de scripts para  procesamiento y análisis de imágenes
-	Entendimiento de los conceptos fundamentales de deep learning aplicado a percepción remota

### METODOLOGIA:
-	Lectura antes de la clase a cargo del estudiante
- Presentación de conceptos, métodos y técnicas a cargo del profesor
-	Realización de ejercicios prácticos y elaboración de reportes técnicos a cargo  del estudiante

### SOFTWARE
-   Python & Jupyter notebooks & Google Colaboratory
:::


## CONTENIDO DETALLADO 

::: {.callout-important collapse=true}

### Unidad 0 –   Repaso de percepción remota en el espectro óptico

### Unidad 1 -  Imágenes térmicas e imágenes hiper-espectrales

### Unidad 2 - Conceptos básicos de radar de apertura sintética

### Unidad 3 – Visualización e interpretación de imágenes SAR 

### Unidad 4 – Pre-procesamiento básico de imágenes SAR 

### Unidad 5 –  Uso de imágenes SAR en aplicaciones ambientales

### Unidad 6 – Principios de aprendizaje profundo 

### Unidad 7 – Segmentación semántica

### Unidad 8 - Modelos fundamentales para datos de observación terrestre
:::


## EVALUACIÓN DEL CURSO: 

::: {.callout-important collapse=false}

-	Presentación de dos exámenes escritos sobre aspectos teóricos (50%)
    - Examen 1 - 19 de Diciembre
    - Examen 2 - 20 de Enero
-	Entrega de dos informes técnicos  (50%)
    - Informe 1 - 16 de Enero
    - Informe 2 - 27 de Febrero

:::

## BIBLIOGRAFIA

::: {.callout-important collapse=true}

Chollet, F. Deep Learning with Python [2nd ed.],  Manning, 2021. 504 pp.

De Grandi, G.D. et al. Spatial Analysis for Radar Remote Sensing of Tropical Forests, CRC Press, 2021. 380pp.

Flores-Anderson, A.I. et al. The Synthetic Aperture Radar (SAR) Handbook: Comprehensive Methodologies for Forest Monitoring and Biomass Estimation,  SERVIR GLOBAL & SilvaCarbon, 2019. 307 pp.

Frery, A.C. et al. SAR Image Analysis - A Computational Statistics Approach: With R Code, Data, and Applications, Wiley-IEEE Press, 2022. 208 pp.

Kamusoko, C., Optical and SAR Remote Sensing of Urban Areas: A Practical Guide, Springer, 2021. 130 pp.

Mandal, D. et al. Radar Remote Sensing for Crop Biophysical Parameter Estimation, Springer, 2021. 236 pp.

Raff, E. Inside Deep Learning – Math, Algorithms, Models,  Manning, 2022. 565 pp.

Rees, W.G. Physical Principles of Remote Sensing [3rd ed.],  Cambridge University Press, 2012. 494 pp.

Richards, J.A. Remote Sensing Digital Image Analysis Sensing [6th ed.], Springer, 2022. 567 pp.

Simms, E.L. SAR Image Interpretation for Various Land Covers – A Practical Guide. CRC Press, 2011. 376 pp. 

Ustin, S.L., and Middleton E.M. Current and near-term advances in Earth observation for ecological applications. Ecological Processes, 2021, 10:1 
Woodhouse, I.H. Introduction to Microwave Remote Sensing, Taylor & Francis, 2022. 370 pp. 

Yamaguchi, Y. Polarimetric SAR imaging: theory and applications. CRC Press, 2020. 350 pp.

:::
