---
subtitle: " 2027449-- PERCEPCION REMOTA AVANZADA"
title: "<font style='font-size:1em;'>🗓️ Week 02<br/> SAR Basics</font>"
author: Ivan Lizarazo(#)
institute: '[Universidad Nacional de Colombia](#)'
date: 16 August 2023
date-meta: 16 August 2023
date-format: "DD MMM YYYY"
toc: true
toc-depth: 1
toc-title: "What we will cover today:"
center-title-slide: false
from: markdown+emoji
format:
  revealjs: 
    fig-responsive: true
    theme: simple
    slide-number: true
    mouse-wheel: false
    preview-links: auto
    logo: /figures/icons/ARS-1.png
    css: /css/styles_slides.css
    footer: '2027449 -- PERCEPCION REMOTA AVANZADA'
---

# Introduction

TBW

# What's RADAR?

Based on the principle of *echolocation*

RAdio Detection and Ranging

# Basic Radar Operation

A pulse of duration $\tau$ travels at the speed of light $c$

The two-way range distance between antena and target is the velocity times the time delay

Thus, the range distance to the target is $R = \frac {c\tau}{2}$

# The Radar Equation

The power leaving the antena ($\P_t$) is shaped by the antenna gain ($G$) and the properties the observed target ($\sigma$), and is reduced by the surface area of a sphere at radius $R$:

$P_t = PtG \frac{\sigma}{\4\piR**2}$

$\sigma$ is know as the backscattering cross-section. It is also denoted as *RCS*.

# Frequency and Wavelength

TBW

# Polarization and scattering

TBW

# Spatial resolution

TBW

# To do before next class 

TBW

## Read this document

TBW

## Watch this video

TBW

## Next practial exercise

TBW